### PR TITLE
Instrument pending timers in tests

### LINKED ISSUE #421: FakeAsync should allow you to get the stack trace of where active timers were created

### PR DESCRIPTION
**Pull request by jamesderlin**
Flutter widget tests assert if a test completes with timers still
pending.  However, it can be hard to diagnose where a pending timer
came from.  For example, a widget might consume a third-party library
that internally uses a timer.

To facilitate this, modify quiver's FakeAsync to store
StackTrace.current when constructing each _FakeTimer.  Add a
pendingTimersDebugInfo getter to to report this.

Fixes #421.

### CODE REVIEW

File: lib/testing/src/async/fake_async.dart [hunk 1]
```diff
@@ -292,4 +301,10 @@ class _FakeTimer implements Timer {
   int get tick {
     throw new UnimplementedError("tick");
   }
+
+  /// Returns debugging information to try to identify the source of the
+  /// [Timer].
+  String get debugInfo =>
```
Comment (yjbanov) [inline lib/testing/src/async/fake_async.dart]: Should we preserve the `StackTrace` to allow downstream code to decide how to filter stack frames?

Comment (jamesderlin) [reply lib/testing/src/async/fake_async.dart]: I think preserving it might be more trouble than it's worth.  Downstream code currently can filter by discarding the first line and using `StackTrace.fromString`; I probably should have explicitly made this part of the contract.
